export default {
  CLEAR_RECIPES: '@@RECIPES_CLEAR',
  API_RECIPES_REQUEST: '@@API/API_RECIPES_LOAD',
  API_RECIPES_SUCCESS: '@@API/API_RECIPES_SUCCESS',
  API_RECIPES_FAILURE: '@@API/API_RECIPES_FAILURE',
};
